# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 409148daf088abecbd9932f6a815e35212b1057640f6fe1d5d7144a06f253a26f3adf6614defe2579ed1088b18637ef93034d3239da1eb483e8cf76b7360730a

test:
  secret_key_base: 2304b56639fa1a1cb862b86affbf242b5d0273d53af00c6ecf177120a1591f11d4f001b25fc0f6e244db0b531e7951929ba1ab27d656ac9e53af03298aa8dfe8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
